=== IRCM/proview/src/main/resources/msanalysis_verifications.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<!--

    Copyright (c) 2006 Institut de recherches cliniques de Montreal (IRCM)

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:annotation>
    <xs:documentation><![CDATA[
    Describes how MS analysis verification list should be written in XML to allow ProView to parse it.
    ]]></xs:documentation>
</xs:annotation>

<xs:element name="verifications">
    <xs:annotation>
        <xs:documentation><![CDATA[
        Verification list group.
        ]]></xs:documentation>
    </xs:annotation>
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="verification" maxOccurs="unbounded" minOccurs="1"/>
        </xs:sequence>
    	<xs:attribute name="type" type="xs:ID" use="required"/>
    </xs:complexType>
</xs:element>
<xs:element name="verification">
    <xs:annotation>
        <xs:documentation><![CDATA[
        Verification to be done before launching MS analysis.
        ]]></xs:documentation>
    </xs:annotation>
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="instrument" maxOccurs="unbounded" minOccurs="1"/>
        </xs:sequence>
    	<xs:attribute name="name" type="xs:ID" use="required"/>
    </xs:complexType>
</xs:element>
<xs:element name="instrument">
    <xs:annotation>
        <xs:documentation><![CDATA[
        Instrument on which verification applies.
        ]]></xs:documentation>
    </xs:annotation>
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="source" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    	<xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>
</xs:element>
<xs:element name="source">
    <xs:annotation>
        <xs:documentation><![CDATA[
        Instrument's source on which verification applies.
        ]]></xs:documentation>
    </xs:annotation>
    <xs:complexType>
    	<xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>
</xs:element>


<!-- Main element -->
<xs:element name="msanalysis">
    <xs:annotation>
        <xs:documentation><![CDATA[
        MS analysis verification list.
        ]]></xs:documentation>
    </xs:annotation>
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="verifications" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:schema>

=== IRCM/proview/src/main/resources/msanalysis_verifications.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (c) 2006 Institut de recherches cliniques de Montreal (IRCM)

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

-->
<msanalysis xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="msanalysis_verifications.xsd">
  <verifications type="INSTRUMENT">
    <verification name="diskSpace">
      <instrument name="VELOS" />
      <instrument name="Q_EXACTIVE" />
      <instrument name="TSQ_VANTAGE" />
      <instrument name="ORBITRAP_FUSION" />
      <instrument name="LTQ_ORBI_TRAP" />
      <instrument name="Q_TOF" />
      <instrument name="TOF" />
    </verification>
    <verification name="qcPassed">
      <instrument name="VELOS" />
      <instrument name="Q_EXACTIVE" />
      <instrument name="TSQ_VANTAGE" />
      <instrument name="ORBITRAP_FUSION" />
      <instrument name="LTQ_ORBI_TRAP" />
      <instrument name="Q_TOF" />
      <instrument name="TOF" />
    </verification>
    <verification name="calibration">
      <instrument name="VELOS" />
      <instrument name="Q_EXACTIVE" />
      <instrument name="TSQ_VANTAGE" />
      <instrument name="ORBITRAP_FUSION" />
      <instrument name="LTQ_ORBI_TRAP" />
      <instrument name="Q_TOF" />
      <instrument name="TOF" />
    </verification>
    <verification name="sonicatedPlaque">
      <instrument name="VELOS" />
      <instrument name="Q_EXACTIVE" />
      <instrument name="TSQ_VANTAGE" />
      <instrument name="ORBITRAP_FUSION" />
      <instrument name="LTQ_ORBI_TRAP" />
      <instrument name="Q_TOF" />
      <instrument name="TOF" />
    </verification>
    <verification name="plaquePositionOnAutoSampler">
      <instrument name="VELOS" />
      <instrument name="Q_EXACTIVE" />
      <instrument name="TSQ_VANTAGE" />
      <instrument name="ORBITRAP_FUSION" />
      <instrument name="LTQ_ORBI_TRAP" />
      <instrument name="Q_TOF" />
      <instrument name="TOF" />
    </verification>
    <verification name="coolerTemperature">
      <instrument name="VELOS" />
      <instrument name="Q_EXACTIVE" />
      <instrument name="TSQ_VANTAGE" />
      <instrument name="ORBITRAP_FUSION" />
      <instrument name="LTQ_ORBI_TRAP" />
      <instrument name="Q_TOF" />
    </verification>
    <verification name="nitrogenQuantity">
      <instrument name="VELOS" />
      <instrument name="Q_EXACTIVE" />
      <instrument name="TSQ_VANTAGE" />
      <instrument name="ORBITRAP_FUSION" />
      <instrument name="LTQ_ORBI_TRAP" />
      <instrument name="Q_TOF" />
      <instrument name="TOF" />
    </verification>
    <verification name="argonQuantity">
      <instrument name="Q_TOF" />
    </verification>
    <verification name="heliumQuantity">
      <instrument name="VELOS" />
      <instrument name="Q_EXACTIVE" />
      <instrument name="TSQ_VANTAGE" />
      <instrument name="ORBITRAP_FUSION" />
      <instrument name="LTQ_ORBI_TRAP" />
    </verification>
    <verification name="mobilePhaseQuantity">
      <instrument name="VELOS" />
      <instrument name="Q_EXACTIVE" />
      <instrument name="TSQ_VANTAGE" />
      <instrument name="ORBITRAP_FUSION" />
      <instrument name="LTQ_ORBI_TRAP" />
      <instrument name="Q_TOF" />
    </verification>
    <verification name="openGaz">
      <instrument name="Q_TOF" />
    </verification>
    <verification name="lcPumpPressure">
      <instrument name="VELOS" />
      <instrument name="Q_EXACTIVE" />
      <instrument name="TSQ_VANTAGE" />
      <instrument name="ORBITRAP_FUSION" />
      <instrument name="LTQ_ORBI_TRAP" />
      <instrument name="Q_TOF" />
    </verification>
    <verification name="vacuum">
      <instrument name="VELOS" />
      <instrument name="Q_EXACTIVE" />
      <instrument name="TSQ_VANTAGE" />
      <instrument name="ORBITRAP_FUSION" />
      <instrument name="LTQ_ORBI_TRAP" />
      <instrument name="Q_TOF" />
      <instrument name="TOF" />
    </verification>
    <verification name="collisionEnergy">
      <instrument name="Q_TOF" />
    </verification>
    <verification name="mcp">
      <instrument name="Q_TOF" />
      <instrument name="TOF" />
    </verification>
    <verification name="uncheckedAutoCid">
      <instrument name="Q_TOF" />
      <instrument name="TOF" />
    </verification>
    <verification name="checkedGhz">
      <instrument name="Q_TOF">
        <source name="NSI" />
        <source name="ESI" />
      </instrument>
      <instrument name="TOF" />
    </verification>
    <verification name="drainingVialVolume">
      <instrument name="VELOS" />
      <instrument name="Q_EXACTIVE" />
      <instrument name="TSQ_VANTAGE" />
      <instrument name="ORBITRAP_FUSION" />
      <instrument name="LTQ_ORBI_TRAP" />
      <instrument name="Q_TOF" />
    </verification>
    <verification name="spray">
      <instrument name="VELOS">
        <source name="NSI" />
        <source name="ESI" />
      </instrument>
      <instrument name="Q_EXACTIVE">
        <source name="NSI" />
        <source name="ESI" />
      </instrument>
      <instrument name="TSQ_VANTAGE">
        <source name="NSI" />
        <source name="ESI" />
      </instrument>
      <instrument name="ORBITRAP_FUSION">
        <source name="NSI" />
        <source name="ESI" />
      </instrument>
      <instrument name="LTQ_ORBI_TRAP">
        <source name="NSI" />
        <source name="ESI" />
      </instrument>
      <instrument name="Q_TOF">
        <source name="NSI" />
        <source name="ESI" />
      </instrument>
      <instrument name="TOF" />
    </verification>
  </verifications>
  <verifications type="SAMPLE">
    <verification name="sampleVsSpot">
      <instrument name="VELOS" />
      <instrument name="Q_EXACTIVE" />
      <instrument name="TSQ_VANTAGE" />
      <instrument name="ORBITRAP_FUSION" />
      <instrument name="LTQ_ORBI_TRAP" />
      <instrument name="Q_TOF" />
      <instrument name="TOF" />
    </verification>
    <verification name="acquisitionFile">
      <instrument name="VELOS" />
      <instrument name="Q_EXACTIVE" />
      <instrument name="TSQ_VANTAGE" />
      <instrument name="ORBITRAP_FUSION" />
      <instrument name="LTQ_ORBI_TRAP" />
    </verification>
    <verification name="clMethod">
      <instrument name="Q_TOF" />
    </verification>
    <verification name="msMethod">
      <instrument name="Q_TOF" />
      <instrument name="TOF" />
    </verification>
    <verification name="volume">
      <instrument name="VELOS">
        <source name="NSI" />
        <source name="ESI" />
      </instrument>
      <instrument name="Q_EXACTIVE">
        <source name="NSI" />
        <source name="ESI" />
      </instrument>
      <instrument name="TSQ_VANTAGE">
        <source name="NSI" />
        <source name="ESI" />
      </instrument>
      <instrument name="ORBITRAP_FUSION">
        <source name="NSI" />
        <source name="ESI" />
      </instrument>
      <instrument name="LTQ_ORBI_TRAP">
        <source name="NSI" />
        <source name="ESI" />
      </instrument>
      <instrument name="Q_TOF">
        <source name="NSI" />
        <source name="ESI" />
      </instrument>
    </verification>
  </verifications>
</msanalysis>
